#+TITLE: Nov 9th, 2020

** [[The Firm]]
*** [[Adam Smith]] (1723 - 1790)
**** The worlds first economist.
**** Published two books;
***** The Theory of Moral Sentiments
***** The Wealth of Nations
**** Economic Theory
***** "By opening a more extensive market for the produce of their labour, it encourages them to improve productive powers and thereby to increase the real revenue and wealth of the society"
***** Free markets and free trade would connect the continents and result in global prosperity.
***** Market development would result in a reduction in poverty. International trade equals prosperity.
***** Believed market forces on their own could alleviate poverty, no need for state intervention so long as the right policies were in place.
***** "Little else is requisite to carry a state to the highest degree of opulence but peace, easy taxes and a tolerable administration of justice; all the rest being brought about by the natural course of things."
***** The productive potential of the division of labour and the power of specialisation;
****** Believed that the division of labour would result in an increase in the productive powers of labour.
****** This has been all but proven today, where the division of labour in many production lines allows for specialisation in specific fields, resulting in a greater rate of production
****** Think different suppliers in different countries making specialised parts to ship to a single factory to assemble into an entire aeroplane.
