#+TITLE: The Firm

** [[Adam Smith]] (1723 - 1790)
**** The worlds first economist.
**** Published two books;
***** The Theory of Moral Sentiments
***** The Wealth of Nations
**** *Adam Smith's [[Economic Theory]]*
***** /"By opening a more extensive market for the produce of their labour, it encourages them to improve productive powers and thereby to increase the real revenue and wealth of the society"/
***** Free markets and free trade would connect the continents and result in global prosperity.
***** Market development would result in a reduction in poverty. International trade equals prosperity.
***** Believed market forces on their own could alleviate poverty, no need for state intervention so long as the right policies were in place.
***** /"Little else is requisite to carry a state to the highest degree of opulence but peace, easy taxes and a tolerable administration of justice; all the rest being brought about by the natural course of things."/
***** The productive potential of the division of labour and the power of specialisation;
****** Believed that the division of labour would result in an increase in the productive powers of labour.
****** This has been all but proven today, where the division of labour in many production lines allows for specialisation in specific fields, resulting in a greater rate of production
****** Think different suppliers in different countries making specialised parts to ship to a single factory to assemble into an entire aeroplane.
****** The larger the scale of cooperation, the greater the chance of specialising.
***** [[Self-interest]] and [[The Invisible Hand]]
****** /"It is not from the benevolence of the butcher, the brewer or the baker that we expect our dinner, but from their regard to their own interest. We address ourselves not to their humanity, but to their self-love and never talk to them of our own necessities but of their advantages."/
****** The Invisible Hand
******* Individuals pursuing their own interest - namely, selling goods and services to make a living - benefits society by providing things citizens need and want.
******* Consider the baker. The baker benefits from selling his bread, but so do his customers. They receive good thats they desire or need in exchange of payment to the baker.
******* Smith understood that the value customers gained from the bread exceeded the price they paid for it. This is called a Value Added Exchange - where both parties are better off after the exchange.
******* Exchanges, however, must be voluntary. Both the seller and the buyer must enter the exchange of their own accord and voluntarily decide that the exchange is in each of their interests.
******* Each party must have an opt-out option, to go elsewhere if they so choose.
******* Both parties must be independent and autonomous.
******* This is why Smith believes the state should not try to control the economy. Just let self-interested individuals trade with one another.
****** Self-interest means that top-down command structures aren't always the best, things organise themselves better from the bottom up.
****** /"The natural effort of every individual to better his own condition is so powerful, that it is alone capable of carrying on the society to wealth and prosperity."/
****** Individual human action is what creates markets, not individual human design - think language, markets etc., all are the results of human action, not desire. No one planned these things, they just evolved naturally.
****** You don't need a central planning authority to run society well.
***** Smith was suspicious of partnerships between business and government.
***** Any institution - including government - may become corrupted if too big and making too many decisions centrally.
***** /"To widen the market and to narrow the competition, is always the interest of the dealers. Any new law of regulation of commerce ought always to be listened to with great precaution."/
***** Whenever someone is lobbying to the government, they are doing so to protect their own interest at the expense of others.
***** In order for competition to work its magic, you need to have rules in place because otherwise, rather than competition, you have the law of the jungle.
***** True competition - the free market - can only occur on a level playing field.
***** Competition is a way of giving the consumer the power over companies.
***** Economic democracy - where decision making is shifted from the managers and shareholders to larger groups of public stakeholders - and fairness enable the free market.
***** The free market - A system in which the prices for goods and services are self-regulated by the open market and by consumers.
***** The invisible hand guides marketplace sellers to sell, through means of their own self-interest.
***** Prices rise because demand increases, the invisible hand guides sellers into the market to satisfy that demand, thus prices settle.
***** /"Public services are never better performed than when their reward comes in consequence of their being performed, and is proportioned to the diligence employed in performing them"/
****** In other words, the review system of eBay means sellers will offer a better service, which will result in positive reviews and thus more profits. A win-win for everybody.
***** The free market is about trust and cooperation with the customers.
***** Society will be better off when motivated individuals with self-interest are competing against one another on the open market than if Government action gets in the way.
***** Let consumers choose what to buy and let producers choose what to sell. Market forces will be better than Government at deciding what things should be worth.
***** The problem of self-interest is that in unregulated markets, however, causes greed, resulting in scams, false advertising etc.
***** Government should allow people to trade freely, with a few but specific robust protections. Much of the actual work of making life better is the work of the individuals;
****** /"Every man is left perfectly free to pursue his own interest in his own way. The sovereign is completely discharged from a duty for which no human wisdom or knowledge could ever be sufficient; the duty of superintending the industry of private people./
** [[Joseph Schumpeter]] (1883 - 1950)
** Uncovered how capitalism 'really works'.
** For decades, he was almost forgotten. But the digital revolution has showcased Schumpeter's ideas - particularly that of [[Creative Destruction]].
** Joseph Schumpeter's [[Economic Theory]]
